Neos:
  Neos:
    fusion:
      autoInclude:
        TdsOnepager.Site: true
    userInterface:
      translation:
        autoInclude:
          'TdsOnepager.Site': ['NodeTypes/*']
      navigateComponent:
        nodeTree:
          loadingDepth: 1
    nodeTypes:
      groups:
        system:
          position: end
          label: System
          collapsed: true

  ContentRepository:
    contentDimensions:
      language:
        country:
          default: 'de'
          defaultPreset: 'de'
          label: 'Land'
          icon: 'icon-globe'
          presets:
            'de':
              label: Deutschland
              values: [ 'de' ]
              uriSegment: ''
        label: 'Sprache'
        icon: icon-language
        default: de
        defaultPreset: de
        presets:
          de:
            label: Deutsch
            values:
              - de
            uriSegment: ''

#  Media:
#    assetSources:
#      pexels:
#        assetSourceOptions:
#          accessKey: 563492ad6f91700001000001b9eaa7f7df5b496ab50231665d784b13
#          copyRightNoticeTemplate: '${"Pexels.com / " + user.name}'
#          defaultSearchTerm: 'medical'
#          proxyUrl: '%env:HTTP_PROXY%'
